### ISSUE TITLE
Make `ocaml-depgraph` available in the opam repository

### ISSUE THREAD

**Issue by esope** [sim642/ocaml-depgraph#1]
I think `ocaml-depgraph` would be a useful tool for the Ocaml community.
What do you think of publishing it on the opam repository?

**Comment by sim642** [comment]
Absolutely, I've had the idea since beginning but lately haven't had time to work on this.

Once concern I still have is the naming, because [depgraph](https://opam.ocaml.org/packages/depgraph/) already exists on opam and an `ocaml-` prefix is annoyingly redundant for most opam packages. Suggestions in this regard are welcome.

**Comment by esope** [comment]
What about using an acronym, then? ODG fir example, for Ocaml Dependency Graph.
Of course, ODG is [used in other contexts already](https://en.wikipedia.org/wiki/ODG)...

**Comment by sim642** [comment]
I thought about the name for a while and came up with `odep`, which has a similar flavor to odoc and odig. I've now done the renaming and am doing chores to get ready for publishing.

**Comment by sim642** [comment]
The initial release is now available on opam: https://opam.ocaml.org/packages/odep/.

**Comment by esope** [comment]
Excellent! Thanks a lot!
